# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

registries:
  github-nuget:
    type: nuget-feed
    url: https://nuget.pkg.github.com/dfe-digital/index.json
    token: "${{secrets.DEPENDABOT_PAT}}"

  official-nuget:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[github-action] "

  - package-ecosystem: "nuget"
    registries:
      - official-nuget
      - github-nuget
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[nuget] "
