# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions: write-all
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Add nuget package source
      run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/DFE-Digital/index.json"
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: fbc6d4c5-887a-4f53-9193-eecf51f2b111
        tenant-id: 9c7d9dd3-840c-4b3f-818e-552865082e16
        subscription-id:  1ca1a2df-f842-48ce-9403-6d9bc4021692 
        enable-AzPSSession: true

    - name: Get Appsettings Key Vault Secrets
      id: aisearch-key
      uses: Azure/get-keyvault-secrets@v1
      with: 
        keyvault: search-prototype-vault
        secrets: 'AzureSearchConnectionOptions--Credentials'
        
    - name: Echo the secret
      run: |
        echo "My Secret: ${{ steps.aisearch-key.outputs.AzureSearchConnectionOptions--Credentials }}" | sed 's/./&/g'
        

    - name: Swap appsettings values
      uses: microsoft/variable-substitution@v1
      with: 
        files: '**/appsettings.*.json'
      env:
        AzureSearchConnectionOptions.Credentials: '${{ steps.aisearch-key.outputs.AzureSearchConnectionOptions--Credentials }}'

    - name: Test
      run: dotnet test --verbosity normal
